sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t adamtestowy/fibonacci -f Dockerfile .

script:
  - docker run -e CI=true adamtestowy/fibonacci npm run start
